scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['195.9.195.14:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['195.9.195.14:9100']

  - job_name: 'cups_nodejs'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'test.goodgame.ru:8001/prom-metrics' ]
