scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.48:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.48:9100']
  - job_name: 'home-assistant_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.1.76:9100' ]
